apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-pipeline
spec:
  tasks:
    - name: build-and-push
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: docker.io/soumil22/rails-app
        - name: CONTEXT
          value: git://github.com/Soumil2002/devops-ror-app.git

